### ISSUE TITLE
Crash, possibly conflict with Biomes O' Plenty?

### ISSUE THREAD

**Issue by hairlessOrphan** [MinimumContent/muon#1] opened 2017-02-11 19:07 UTC
Crash occurred while I was flying around a test world to take a look around. Stack trace attached!

Description: Exception preparing structure feature

java.lang.NullPointerException: Exception preparing structure feature
	at gd.izno.mc.muon.MuonUtils.biasBoundingBox(MuonUtils.java:46)
	at gd.izno.mc.muon.MuonHooks.villageModTerrain(MuonHooks.java:346)
	at net.minecraft.world.gen.structure.MapGenVillage$Start.<init>(SourceFile:114)
	at net.minecraft.world.gen.structure.MapGenVillage.func_75049_b(SourceFile:78)
	at net.minecraft.world.gen.structure.MapGenStructure.func_180701_a(MapGenStructure.java:39)
	at net.minecraft.world.gen.MapGenBase.func_186125_a(SourceFile:27)
	at biomesoplenty.common.world.ChunkProviderGenerateBOP.func_185932_a(ChunkProviderGenerateBOP.java:165)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:140)
	at net.minecraft.world.World.func_72964_e(World.java:303)
	at net.minecraft.world.World.func_175726_f(World.java:298)
	at net.minecraft.world.World.func_180495_p(World.java:842)
	at net.minecraft.world.gen.feature.WorldGenMinable.func_180709_b(WorldGenMinable.java:76)
	at vazkii.quark.world.world.StoneInfoBasedGenerator.generate(StoneInfoBasedGenerator.java:59)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:969)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at gd.izno.mc.muon.MuonUtils.biasBoundingBox(MuonUtils.java:46)
	at gd.izno.mc.muon.MuonHooks.villageModTerrain(MuonHooks.java:346)
	at net.minecraft.world.gen.structure.MapGenVillage$Start.<init>(SourceFile:114)
	at net.minecraft.world.gen.structure.MapGenVillage.func_75049_b(SourceFile:78)

-- Feature being prepared --
Details:
	Is feature chunk: True
	Chunk location: 41,-14
	Chunk pos hash: -60129542103
	Structure type: net.minecraft.world.gen.structure.MapGenVillage
Stacktrace:
	at net.minecraft.world.gen.structure.MapGenStructure.func_180701_a(MapGenStructure.java:39)
	at net.minecraft.world.gen.MapGenBase.func_186125_a(SourceFile:27)
	at biomesoplenty.common.world.ChunkProviderGenerateBOP.func_185932_a(ChunkProviderGenerateBOP.java:165)

-- Chunk to be generated --
Details:
	Location: 43,-6
	Position hash: -25769803733
	Generator: biomesoplenty.common.world.ChunkProviderGenerateBOP@423aeeeb
Stacktrace:
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:140)
	at net.minecraft.world.World.func_72964_e(World.java:303)
	at net.minecraft.world.World.func_175726_f(World.java:298)
	at net.minecraft.world.World.func_180495_p(World.java:842)
	at net.minecraft.world.gen.feature.WorldGenMinable.func_180709_b(WorldGenMinable.java:76)
	at vazkii.quark.world.world.StoneInfoBasedGenerator.generate(StoneInfoBasedGenerator.java:59)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:969)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)

**Comment by hairlessOrphan** [comment] 2017-02-12 00:21
I'm an idiot, sorry; this crash may be caused by interplay with several different mods. I thought I got it on my testing profile with just this and BoP, but I actually experienced it on a profile that had several mods, including Recurrent Complex and Ruins (SSS). What can I do to help debug this?

**Comment by TrinaryLogic** [comment] 2017-02-13 14:03
Thanks for letting me know about this and posting all the info. :)
I will dig into the code and look for any likely culprits.
In the meantime, anything you can do to work out how to reliably reproduce this crash would be awesome help in assuring it was fixed. :)
One question I did think of, was this world saved, exited, and reloaded at any point prior to the crash?

**Comment by hairlessOrphan** [comment] 2017-02-13 16:00
Was not saved or exited. Right after creating the world, flying around to find a village.

I'm 90% sure I've nailed down the conflict to... Pokecube. When it tries to add its two special village buildings. But I haven't had a chance to try an isolated install with just this and Pokecube and try it.

**Comment by TrinaryLogic** [comment] 2017-02-15 23:46
Thanks for the info, I have managed to reliably reproduce this with the pokecube modpack.  :)
The problem was not correctly handling modded buildings that did not have a facing direction.
I have fixed this locally and confirmed it works, and should have the new version up soon. :)

**Comment by hairlessOrphan** [comment] 2017-02-18 07:12
Not that I'm impatient... but knowing your mod is out there makes vanilla village gen intolerable. :D Looking forward to the patch update! Thanks!

**Comment by TrinaryLogic** [comment] 2017-03-15 23:58
Muon 0.2 has finally been released and contains the fix for this issue. It will be available on Curseforge soon :)

**Closed as completed by TrinaryLogic** 2017-03-15 23:58 UTC
